Check for crm_node presence before collecting fact
This commit adds a check to make sure 'crm_node' is present on the
system (or inside a container, fwiw) before attempting to collect
the stonith level info, so preventing errors like:

~~~
Error: Facter: error while resolving custom fact
\"stonith_levels\": execution of command \"crm_node -n 2> /dev/null\"
failed: command not found."
~~~

Change-Id: I4b4304b54a8aec76fad50b503a007b2bfcc41bd1
(cherry picked from commit 57ef37990a03bf8cbd99383544699b367b23c625)