Make the 'Could not find data item hacluster_pwd' error a bit clearer
If you deploy a role with a pacemaker-managed service (galera, rabbit, redis,
etc) but forgot to add the ::tripleo::profile::base::pacemaker
there will be a rather unintuitive error:
  puppet apply --debug --verbose --detailed-exitcodes --summarize --color=false --modulepath
    /etc/puppet/modules:/opt/stack/puppet-modules:/usr/share/openstack-puppet/module --tags
    file,file_line,concat,augeas,pacemaker::resource::bundle,pacemaker::property,pacemaker::resource::ocf,pacemaker::constraint::order,pacemaker::constraint::colocation
    -e 'include ::tripleo::profile::base::pacemaker;include ::tripleo::profile::pacemaker::database::redis_bundle'",
  Error: Evaluation Error: Error while evaluating a Function
  Call, Could not find data item hacluster_pwd in any Hiera data file and no default supplied at
  /etc/puppet/modules/tripleo/manifests/profile/base/pacemaker.pp:127:24 on node role-2.localdomain

Let's make it a bit clearer. Long-term we want to look at a validation
that covers this.

Change-Id: Iffb6e76cdd0286ef10ada57c70ce31971e42c84f