Require the UI package when creating the virtual host
Quickstart is failing with this error:

Error: Cannot create /var/www/openstack-tripleo-ui/dist;
       parent directory /var/www/openstack-tripleo-ui does not exist
Error: /Stage[main]/Tripleo::Ui/Apache::Vhost[tripleo-ui]/File[/var/www/openstack-tripleo-ui/dist]
       ensure: change from absent to directory
       failed: Cannot create /var/www/openstack-tripleo-ui/dist; parent directory /var/www/openstack-tripleo-ui does not exist

Puppet cant create the folders tree by itself.

Closes-bug: 1698105
Change-Id: I5cce963a6225552f4b7253cb34edc72b392b9dda